version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: fsw-foods-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - C:\Users\danie\Documents\docker\.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data: